language: python
dist: trusty
sudo: required

python:
    - "3.5"

before_install:
    - source travis_env_init.sh

install:
    - pip install -r requirements.txt --timeout 600

script:
    - packages="BaiduSpeech,ConfigFileInfoParser,WaveOperate,WebCurl"
    - python -m nose -s --with-coverage --cover-package=$packages

after_success:
    coveralls

notifications:
    email: true
